#!/usr/bin/env node
// Assemble the static v0.3.0 package. The PMTiles archives and their proof
// directories are generated by veritiles' published pack tool and checked here
// through the released client before they are published.
import { Buffer } from 'node:buffer';
import { copyFile, cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CID } from 'multiformats/cid';
import { sha256 } from 'multiformats/hashes/sha2';
import { VerifiedAsset, VerifiedSource } from 'veritiles';

import { directoryFetch } from './lib/local-fetch.js';
import { parseArchive } from './lib/pmtiles-parse.js';
import { buildStyle } from './lib/style.js';

const RAW_CODE = 0x55;
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = join(repoRoot, 'data');
const distDir = join(repoRoot, 'dist');

const anchors = {
  map: 'bafyreifxbxeu4m3xedbpgq5tx4k4ud4j2wxcpikg5dyzdxdhhy6zvcwo3u',
  elevation: 'bafyreiacny7rdvqj32fil5yxzvcurg6xb5bnhxn3zt53lemoala23x2hai',
  fonts: 'bafyreigr3kszmxht36pxnoddfdraxqnyy4x7ylnqyfnubenpdyqftozamm',
};

async function main() {
  const mapBytes = await readFile(join(dataDir, 'map.pmtiles'));
  const elevationBytes = await readFile(join(dataDir, 'elevation.pmtiles'));
  const elevation = parseArchive(elevationBytes);
  const style = buildStyle({
    mapAnchor: anchors.map,
    fontsAnchor: anchors.fonts,
    elevationMaxZoom: elevation.header.maxZoom,
  });
  const styleBytes = Buffer.from(`${JSON.stringify(style, null, 2)}\n`);
  const styleCid = CID.createV1(RAW_CODE, await sha256.digest(styleBytes)).toString();

  await rm(distDir, { recursive: true, force: true });
  await mkdir(distDir, { recursive: true });
  await copyFile(join(dataDir, 'map.pmtiles'), join(distDir, 'map.pmtiles'));
  await cp(join(dataDir, 'map.pmtiles.proofs'), join(distDir, 'map.pmtiles.proofs'), { recursive: true });
  await copyFile(join(dataDir, 'elevation.pmtiles'), join(distDir, 'elevation.pmtiles'));
  await cp(join(dataDir, 'elevation.pmtiles.proofs'), join(distDir, 'elevation.pmtiles.proofs'), { recursive: true });
  await mkdir(join(distDir, 'assets'), { recursive: true });
  await cp(join(dataDir, 'fonts'), join(distDir, 'assets', 'fonts'), { recursive: true });
  await copyFile(join(dataDir, 'fonts.car'), join(distDir, 'assets', 'fonts.car'));
  await writeFile(join(distDir, 'assets', 'style.json'), styleBytes);
  await mkdir(join(distDir, 'vendor'), { recursive: true });
  await copyFile(join(repoRoot, 'node_modules', 'veritiles', 'dist', 'index.js'), join(distDir, 'vendor', 'veritiles.js'));

  const pageTemplate = await readFile(join(repoRoot, 'index.html'), 'utf8');
  const stylePlaceholder = "style:     'STYLE_CID'";
  if (pageTemplate.split(stylePlaceholder).length !== 2) {
    throw new Error('index.html must contain exactly one style CID placeholder');
  }
  const page = pageTemplate.replace(stylePlaceholder, `style:     '${styleCid}'`);
  await writeFile(join(distDir, 'index.html'), page);

  const fetchFn = directoryFetch(distDir);
  await verifyArchive(anchors.map, 'map.pmtiles', mapBytes, fetchFn);
  await verifyArchive(anchors.elevation, 'elevation.pmtiles', elevationBytes, fetchFn);
  await verifyAssets(styleCid, style, fetchFn);
  console.log(`MAP_ANCHOR ${anchors.map}`);
  console.log(`ELEVATION_ANCHOR ${anchors.elevation}`);
  console.log(`FONTS_ANCHOR ${anchors.fonts}`);
  console.log(`STYLE_CID ${styleCid}`);
  console.log('dist/: every archive, proof, style, and font asset verified with veritiles v0.3.0');
}

async function verifyArchive(cid, source, expected, fetchFn) {
  const file = new VerifiedSource({ cid, source, fetchFn });
  await file.ready();
  for (const [offset, length] of [[0, 16384], [Math.floor(expected.length / 2), 4096], [expected.length - 4096, 4096]]) {
    const got = new Uint8Array((await file.getBytes(offset, length)).data);
    const want = expected.subarray(offset, offset + length);
    if (!Buffer.from(got).equals(want)) throw new Error(`${source}: verified range differs from input`);
  }
}

async function verifyAssets(styleCid, style, fetchFn) {
  const styleAsset = new VerifiedAsset({ cid: styleCid, source: 'assets/style.json', fetchFn });
  const parsed = JSON.parse(new TextDecoder().decode(await styleAsset.bytes()));
  if (parsed.sources['pmtiles-source'].url !== style.sources['pmtiles-source'].url) throw new Error('style asset did not round-trip');
  const fonts = new VerifiedAsset({ cid: anchors.fonts, source: 'assets/fonts', fetchFn });
  const glyph = await fonts.bytes('Noto Sans Regular/0-255.pbf');
  const expected = await readFile(join(dataDir, 'fonts', 'Noto Sans Regular', '0-255.pbf'));
  if (!Buffer.from(glyph).equals(expected)) throw new Error('font asset did not round-trip');
}

await main();
